language: python

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy

install:
    - pip install --upgrade pip setuptools
    - pip install -e .
    - pip install tox
    - pip install coveralls

script:
    - tox

after_success:
    - coveralls
